### ISSUE TITLE
Initialize the comments please

### ISSUE THREAD

**Issue by suntong** [halfrost/S2#833]
> Related Issues not found
> Please contact @halfrost to initialize the comment

please initialize the comment for 
https://books.halfrost.com/leetcode/ChapterFour/1200~1299/1260.Shift-2D-Grid/

thx @halfrost

**Comment by suntong** [comment]
And many others if not yet initialized please.

**Comment by halfrost** [comment]
> > Related Issues not found
> > Please contact @halfrost to initialize the comment
> 
> please initialize the comment for https://books.halfrost.com/leetcode/ChapterFour/1200~1299/1260.Shift-2D-Grid/
> 
> thx @halfrost

@suntong Hi, 1260 has been initialized. Done.

**Comment by suntong** [comment]
wow, that's fast thx a lot @halfrost
